CREATE TABLE IF NOT EXISTS mpa_ratings (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying
);

CREATE TABLE IF NOT EXISTS films
(
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name character varying,
    description text,
    release_date date,
    duration integer,
    mpa_rating_id integer REFERENCES mpa_ratings (id)
);

CREATE TABLE IF NOT EXISTS users (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email character varying,
  login character varying,
  name character varying,
  birthday date
);

CREATE TABLE IF NOT EXISTS genres (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name character varying
);

CREATE TABLE IF NOT EXISTS film_genre (
  film_id integer REFERENCES films (id) ON DELETE CASCADE,
  genre_id integer REFERENCES genres (id),
  PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS friends (
  user_id integer REFERENCES users (id) ON DELETE CASCADE,
  friend_id integer REFERENCES users (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, friend_id),
  CONSTRAINT yourself CHECK (user_id <> friend_id)
);

CREATE TABLE IF NOT EXISTS likes (
  user_id integer REFERENCES users (id) ON DELETE CASCADE,
  film_id integer REFERENCES films (id) ON DELETE CASCADE,
  PRIMARY KEY (user_id, film_id)
);